FROM openjdk:11-jre
COPY . /Console-Tech-Consulting/API/local-app/target/local-app-1.0-SNAPSHOT-jar-with-dependencies.jar/
RUN chmod 777 local-app-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD ["java", "-jar", "local-app-1.0-SNAPSHOT-jar-with-dependencies.jar"]